sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.2
services:
- memcached
before_install:
- gem install bundler
before_script:
- bundle install
- psql -c 'create database epets_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:structure:load
script: bundle exec rake
after_success: bundle exec rake deploy:preview
env:
  global:
  - secure: GZcFHsETJ6372Z6NgWpyjB/xEjGvvN07mbG7xTMeitJ55AkloeurERxiZuteNo6Ak1OlgR/4RrFPO1lA4yk14DEAeRLrduy6X3vLCZyBj4EOZTc7r4hwhpxaeJQR5WqTzmoEoxsYazSoI7BB8xiH695lZzyxOOZUf/ORhb5oQUg=
  - secure: EqzCmbBowkzG8RHnoeem6JOnUK89V47OXwzVAwohb4Txc3M3Adu8yH4yuMX7SwFFiFpkMILFFR7yziEVrr6kZI0ctSIGVPnhhN4QFuiHCdDd4Fd3EIXDzz1eIP1sthOMBxd7bfsaseoAwPinkOm8nsSQlRHpapkGGdt73S2Uc5s=
  - secure: oNgLEqQYQVnT+PkAqcRoEwrdlASqEcXbMXCVPbCi5GUwrQAqyT+3VkJzvg8DEgrO86nHM02usEKDeF6R458Oa2ilbH8k8NUrgKEx05WkSt7kMQxDFN9jbFmLhyjliebcizE2oq/J7yg66GlA8aSBN2NpAGs5WYor/iV5oiWK1w4=
  - secure: ZMlmAdW8L6Xy0NAi2/KtHkHXav7CpgugQVJ3zSy0qp/ysdDBPVEUMrf8714otm7mG8nIYvU0owC78mNqjlFMIsD2MT7p2Kz0+l1MKwc9dV/j7NfUYvD+kveCglFfu1Gzopn73diYN2KZnwbpIR47USExbB2Hb6CYmQj54GuYdCs=
