dist: xenial
language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.5.5

services:
  - memcached
  - postgresql

addons:
  chrome: stable
  postgresql: "10"

before_install:
  - gem install bundler -v 1.17.3

before_script:
  - bundle install
  - psql -c 'create database epets_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:structure:load

script: RAILS_ENV=test bundle exec rake
after_success: bundle exec rake deploy:preview

env:
  global:
    - secure: hQTk4ylIIdlGDl2fJTfbnzfjO0GZlWczkXxall0Af3NLIWlQ8ILyigsopJJMdOOhHk+uTkfmdYTShNcpyXi81HiTjf6uVySvJJm6zwTz9EYGM4qpu+Xlo+2JYCMYWxGlnu3dHcn59s4hf+zh5Ok7BjYRqQA2d0q0wcrtVD2WqSc=
    - secure: f32DRInVTE/8FS/5Q9PlKyxEosL4AUE/MsfMwFeQ+fZ2sjQm14QWDjwmCiah+iIT8QpzWbQDSZnEaqoJyOtwmcJCSBFhzNuqA7CK4mmWW9L0LGojfCDpPSMHsoFdbkKxs83vrCx9dsAQ6lTqWgARoJqwyL80ppXPDu2Soa7WVvo=
    - secure: o+ShV9oLB4vVUbKk4FuNAJDFGywyCgsDcPbFdu9wpF/R7hhEV+CYCyeRM8JpobJ6Ubnl+ilL0eoDseG1BJQrHN+dO/t/FurIeWr74Vh2xf0M6DObtOOP4FIwqQqIlHAZnmNxCb3wzMJHBMUMOyu08ocz8iJRjiS92cDRAnPEop8=
    - secure: N2NnZf2vA9kfPw5JDXndWb2tJ26CwHka4+UO++MRKkvtNtPLsaBZ2lA44woJCqZugLoZcFEDkNc0ff3oOSiAxD/CcQt5budHglYi35BLvuisXmMmezAS/TLo5D+rt5lESl2w8S5MV7Cv73erGIkVs4BMBzNU67t0ZJCy0Vlvdos=
