defaults: &defaults
  email_from: "no-reply@example.gov"
  memcached_servers:
    - "localhost:11211"
  memcached_namespace_base: "e_petitions"
  email_encryption_key: 'notasecret'
  sponsor_count_min: 5
  sponsor_count_max: 20	
  

development:
  <<: *defaults
  host_for_email: "localhost:3000"

development_with_caching:
  <<: *defaults
  host_for_email: "localhost:3000"

test:
  <<: *defaults
  host_for_email: "www.example.com"
