head:
  keys:
    - :translations_updated_at
    - :locale
    - :site_updated_at
    - :url
  options:
    expires_in: 300

footer:
  keys:
    - :translations_updated_at
    - :locale
    - :site_updated_at
    - :create_petition_page
    - :open_petition_page
    - :holding_page
  options:
    expires_in: 300

home_page:
  keys:
    - :translations_updated_at
    - :locale
    - :site_updated_at
    - :last_debate_outcome_updated_at
  options:
    expires_in: 300

local_petitions_page:
  keys:
    - :translations_updated_at
    - :locale
    - :constituency
  options:
    expires_in: 300

all_local_petitions_page:
  keys:
    - :translations_updated_at
    - :locale
    - :constituency
  options:
    expires_in: 300

petition:
  keys:
    - :translations_updated_at
    - :locale
    - :petition
    - :site_updated_at
  options:
    expires_in: 300

robots:
  keys:
    - :translations_updated_at
    - :locale
    - :last_petition_created_at
  options:
    expires_in: 86400
