head:
  keys:
    - :site_updated_at
    - :url
  options:
    expires_in: 300

header:
  keys:
    - :home_page
  options:
    expires_in: 300

footer:
  keys:
    - :create_petition_page
  options:
    expires_in: 300

home_page:
  keys:
    - :last_signature_at
    - :last_government_response_updated_at
    - :last_debate_outcome_updated_at
  options:
    expires_in: 300

petition:
  keys:
    - :petition
    - :reveal_response
  options:
    expires_in: 300

robots:
  keys:
    - :last_petition_created_at
  options:
    expires_in: 86400
