name: Build

on:
  workflow_call:
    inputs:
      description:
        type: string
        required: true
      command:
        type: string
        required: true
      spec_opts:
        type: string
        required: false
        default: ""
      cucumber_format:
        type: string
        required: false
        default: ""
      cucumber_opts:
        type: string
        required: false
        default: ""
      save_screenshots:
        type: boolean
        required: false
        default: false
      save_logs:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: pgvector/pgvector:pg16
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          PGUSER: postgres
          PGPASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update repository lists
        shell: bash
        run: |
          sudo apt-get update

      - name: Install packages
        shell: bash
        run: |
          sudo apt-get -yqq install libpq-dev imagemagick libvips

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          cache-version: 1

      - name: Setup database
        shell: bash
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/epets_test
          RAILS_ENV: test
        run: |
          bundle exec rake db:setup

      - name: Save screenshots
        if: ${{ inputs.save_screenshots && failure() }}
        uses: actions/upload-artifact@v5
        with:
          name: selenium-screenshots-public
          path: ${{ github.workspace }}/tmp/capybara/*.png
          retention-days: 7
          if-no-files-found: ignore

      - name: Save rails logs
        if: ${{ inputs.save_logs && failure() }}
        uses: actions/upload-artifact@v5
        with:
          name: rails-logs-public
          path: ${{ github.workspace }}/log/test.log
          retention-days: 7
          if-no-files-found: ignore

      - name: ${{ inputs.description }}
        shell: bash
        env:
          CUCUMBER_FORMAT: "${{ inputs.cucumber_format }}"
          CUCUMBER_OPTS: "${{ inputs.cucumber_opts }}"
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/epets_test
          RAILS_ENV: test
          SPEC_OPTS: "${{ inputs.spec_opts }}"
        run: |
          bundle exec ${{ inputs.command }}
