name: Deploy to Preview

on:
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    environment:
      name: welsh-petitions-preview
      url: https://petitions-beta.senedd.wales

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"

    - name: Install postgres client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Setup gem cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ubuntu-22.04-gems-${{ hashFiles('/Gemfile.lock') }}
        restore-keys: |
          ubuntu-22.04-gems-

    - name: Install gems
      run: |
        gem install bundler -v 2.3.26
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Deploy application
      env:
        APPSIGNAL_APP_NAME: welsh-petitions-preview
        APPSIGNAL_PUSH_API_KEY: ${{ secrets.APPSIGNAL_PUSH_API_KEY }}
      run: |
        bundle exec rake deploy:preview
